export type MockRecord = Record<string, string | number | boolean | null>;

export type MockDataset = {
    schemaId: string;
    records: MockRecord[];
};

export const MOCK_DATASETS: MockDataset[] = [
    {
        schemaId: "users",
        records: [
            {
                name: "Ada Lovelace",
                email: "ada@example.com",
                age: 28,
                country: "Nigeria",
                status: "active",
                isVerified: true,
                createdAt: "2026-01-12",
                purchases: 14,
            },
            {
                name: "Kofi Mensah",
                email: "kofi@example.com",
                age: 17,
                country: "Ghana",
                status: "pending",
                isVerified: false,
                createdAt: "2026-02-03",
                purchases: 2,
            },
            {
                name: "Amina Yusuf",
                email: "amina@example.com",
                age: 34,
                country: "Nigeria",
                status: "active",
                isVerified: true,
                createdAt: "2025-12-18",
                purchases: 23,
            },
            {
                name: "Thabo Mbeki",
                email: "thabo@example.com",
                age: 42,
                country: "South Africa",
                status: "inactive",
                isVerified: true,
                createdAt: "2025-11-08",
                purchases: 5,
            },
            {
                name: "Grace Kimani",
                email: "grace@example.com",
                age: 25,
                country: "Kenya",
                status: "active",
                isVerified: false,
                createdAt: "2026-03-21",
                purchases: 9,
            },
            {
                name: "Liam Carter",
                email: "liam@example.com",
                age: 31,
                country: "United Kingdom",
                status: "suspended",
                isVerified: true,
                createdAt: "2026-04-04",
                purchases: 0,
            },
            {
                name: "Dreadhead Zero",
                email: "dreadhead@example.com",
                age: 22,
                country: "Nigeria",
                status: "active",
                isVerified: true,
                createdAt: "2026-05-01",
                purchases: 18,
            },
            {
                name: "Maya Okafor",
                email: "maya@example.com",
                age: 19,
                country: "Nigeria",
                status: "pending",
                isVerified: false,
                createdAt: "2026-05-14",
                purchases: 4,
            },
        ],
    },
    {
        schemaId: "orders",
        records: [
            {
                orderId: "ORD-1001",
                customerName: "Ada Lovelace",
                total: 250,
                status: "paid",
                paymentMethod: "card",
                createdAt: "2026-01-15",
                isPriority: true,
            },
            {
                orderId: "ORD-1002",
                customerName: "Kofi Mensah",
                total: 75,
                status: "pending",
                paymentMethod: "bank_transfer",
                createdAt: "2026-02-06",
                isPriority: false,
            },
            {
                orderId: "ORD-1003",
                customerName: "Amina Yusuf",
                total: 520,
                status: "shipped",
                paymentMethod: "wallet",
                createdAt: "2026-03-11",
                isPriority: true,
            },
            {
                orderId: "ORD-1004",
                customerName: "Grace Kimani",
                total: 120,
                status: "delivered",
                paymentMethod: "cash",
                createdAt: "2026-04-02",
                isPriority: false,
            },
            {
                orderId: "ORD-1005",
                customerName: "Liam Carter",
                total: 40,
                status: "cancelled",
                paymentMethod: "card",
                createdAt: "2026-04-20",
                isPriority: false,
            },
        ],
    },
    {
        schemaId: "products",
        records: [
            {
                title: "Wireless Keyboard",
                category: "electronics",
                price: 45,
                stock: 120,
                isPublished: true,
                createdAt: "2026-01-01",
            },
            {
                title: "Cotton Hoodie",
                category: "fashion",
                price: 35,
                stock: 64,
                isPublished: true,
                createdAt: "2026-01-18",
            },
            {
                title: "Face Serum",
                category: "beauty",
                price: 22,
                stock: 0,
                isPublished: false,
                createdAt: "2026-02-14",
            },
            {
                title: "Desk Lamp",
                category: "home",
                price: 55,
                stock: 30,
                isPublished: true,
                createdAt: "2026-03-09",
            },
            {
                title: "TypeScript Handbook",
                category: "books",
                price: 18,
                stock: 200,
                isPublished: true,
                createdAt: "2026-04-25",
            },
        ],
    },
];

export function getMockDatasetBySchemaId(schemaId: string) {
    return MOCK_DATASETS.find((dataset) => dataset.schemaId === schemaId);
}